
package me.heldplayer.HeldGeneration.GenLayers;

import me.heldplayer.HeldGeneration.helpers.BiomeHelp;

public class GenLayerRiverMix extends GenLayer {
    private GenLayer riverLayer;
    private GenLayer hillsLayer;

    public GenLayerRiverMix(long seed, GenLayer riverLayer, GenLayer hillsLayer) {
        super(seed);
        this.riverLayer = riverLayer;
        this.hillsLayer = hillsLayer;
    }

    /**
     * Initialize layer's local worldGenSeed based on its own baseSeed and the
     * world's global seed (passed in as an
     * argument).
     */
    @Override
    public void initWorldGenSeed(long seed) {
        this.riverLayer.initWorldGenSeed(seed);
        this.hillsLayer.initWorldGenSeed(seed);
        super.initWorldGenSeed(seed);
    }

    /**
     * Returns a list of integer values generated by this layer. These may be
     * interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer
     * subclass.
     */
    @Override
    public int[] getInts(int startX, int startZ, int sizeX, int sizeZ) {
        int[] var5 = this.riverLayer.getInts(startX, startZ, sizeX, sizeZ);
        int[] var6 = this.hillsLayer.getInts(startX, startZ, sizeX, sizeZ);
        int[] var7 = IntCache.getIntCache(sizeX * sizeZ);

        for (int var8 = 0; var8 < sizeX * sizeZ; ++var8) {
            if (var5[var8] == BiomeHelp.OCEAN.id) {
                var7[var8] = var5[var8];
            }
            else if (var6[var8] >= 0) {
                if (var5[var8] == BiomeHelp.ICE_PLAINS.id) {
                    var7[var8] = BiomeHelp.FROZEN_RIVER.id;
                }
                else if (var5[var8] != BiomeHelp.MUSHROOM_ISLAND.id && var5[var8] != BiomeHelp.MUSHROOM_ISLAND_SHORE.id) {
                    var7[var8] = var6[var8];
                }
                else {
                    var7[var8] = BiomeHelp.MUSHROOM_ISLAND_SHORE.id;
                }
            }
            else {
                var7[var8] = var5[var8];
            }
        }

        return var7;
    }
}
