
package me.heldplayer.HeldGeneration.GenLayers;

public class GenLayerRiverInit extends GenLayer {
    public GenLayerRiverInit(long seed, GenLayer parent) {
        super(seed);
        this.parent = parent;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be
     * interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer
     * subclass.
     */
    @Override
    public int[] getInts(int startX, int startZ, int sizeX, int sizeZ) {
        int[] var5 = this.parent.getInts(startX, startZ, sizeX, sizeZ);
        int[] var6 = IntCache.getIntCache(sizeX * sizeZ);

        for (int var7 = 0; var7 < sizeZ; ++var7) {
            for (int var8 = 0; var8 < sizeX; ++var8) {
                initChunkSeed((var8 + startX), (var7 + startZ));
                var6[var8 + var7 * sizeX] = var5[var8 + var7 * sizeX] > 0 ? nextInt(2) + 2 : 0;
            }
        }

        return var6;
    }
}
