
package me.heldplayer.HeldGeneration.GenLayers;

public class GenLayerSmooth extends GenLayer {
    public GenLayerSmooth(long seed, GenLayer parent) {
        super(seed);
        super.parent = parent;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be
     * interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer
     * subclass.
     */
    @Override
    public int[] getInts(int startX, int startZ, int sizeX, int sizeZ) {
        int var5 = startX - 1;
        int var6 = startZ - 1;
        int var7 = sizeX + 2;
        int var8 = sizeZ + 2;
        int[] var9 = this.parent.getInts(var5, var6, var7, var8);
        int[] var10 = IntCache.getIntCache(sizeX * sizeZ);

        for (int var11 = 0; var11 < sizeZ; ++var11) {
            for (int var12 = 0; var12 < sizeX; ++var12) {
                int var13 = var9[var12 + 0 + (var11 + 1) * var7];
                int var14 = var9[var12 + 2 + (var11 + 1) * var7];
                int var15 = var9[var12 + 1 + (var11 + 0) * var7];
                int var16 = var9[var12 + 1 + (var11 + 2) * var7];
                int var17 = var9[var12 + 1 + (var11 + 1) * var7];

                if (var13 == var14 && var15 == var16) {
                    initChunkSeed((var12 + startX), (var11 + startZ));

                    if (nextInt(2) == 0) {
                        var17 = var13;
                    }
                    else {
                        var17 = var15;
                    }
                }
                else {
                    if (var13 == var14) {
                        var17 = var13;
                    }

                    if (var15 == var16) {
                        var17 = var15;
                    }
                }

                var10[var12 + var11 * sizeX] = var17;
            }
        }

        return var10;
    }
}
