
package me.heldplayer.HeldGeneration.GenLayers;

import me.heldplayer.HeldGeneration.helpers.BiomeHelp;

public class GenLayerAddSnow extends GenLayer {
    public GenLayerAddSnow(long seed, GenLayer parent) {
        super(seed);
        this.parent = parent;
    }

    /**
     * Returns a list of integer values generated by this layer. These may be
     * interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer
     * subclass.
     */
    @Override
    public int[] getInts(int startX, int startZ, int sizeX, int sizeZ) {
        int var5 = startX - 1;
        int var6 = startZ - 1;
        int var7 = sizeX + 2;
        int var8 = sizeZ + 2;
        int[] var9 = this.parent.getInts(var5, var6, var7, var8);
        int[] var10 = IntCache.getIntCache(sizeX * sizeZ);

        for (int var11 = 0; var11 < sizeZ; ++var11) {
            for (int var12 = 0; var12 < sizeX; ++var12) {
                int var13 = var9[var12 + 1 + (var11 + 1) * var7];
                initChunkSeed((var12 + startX), (var11 + startZ));

                if (var13 == 0) {
                    var10[var12 + var11 * sizeX] = 0;
                }
                else {
                    int var14 = nextInt(5);

                    if (var14 == 0) {
                        var14 = BiomeHelp.ICE_PLAINS.id;
                    }
                    else {
                        var14 = 1;
                    }

                    var10[var12 + var11 * sizeX] = var14;
                }
            }
        }

        return var10;
    }
}
