package me.heldplayer.HeldGeneration.GenLayers;

import me.heldplayer.HeldGeneration.helpers.BiomeHelp;

public class GenLayerHills extends GenLayer {
	public GenLayerHills(long seed, GenLayer parent) {
		super(seed);
		this.parent = parent;
	}

	/**
	 * Returns a list of integer values generated by this layer. These may be
	 * interpreted as temperatures, rainfall
	 * amounts, or biomeList[] indices based on the particular GenLayer
	 * subclass.
	 */
	@Override
	public int[] getInts(int startX, int startZ, int sizeX, int sizeZ) {
		int[] var5 = this.parent.getInts(startX - 1, startZ - 1, sizeX + 2, sizeZ + 2);
		int[] var6 = IntCache.getIntCache(sizeX * sizeZ);

		for (int var7 = 0; var7 < sizeZ; ++var7) {
			for (int var8 = 0; var8 < sizeX; ++var8) {
				initChunkSeed((var8 + startX), (var7 + startZ));
				int var9 = var5[var8 + 1 + (var7 + 1) * (sizeX + 2)];

				if (nextInt(3) == 0) {
					int var10 = var9;

					if (var9 == BiomeHelp.DESERT.id) {
						var10 = BiomeHelp.DESERT_HILLS.id;
					} else if (var9 == BiomeHelp.FOREST.id) {
						var10 = BiomeHelp.FOREST_HILLS.id;
					} else if (var9 == BiomeHelp.TAIGA.id) {
						var10 = BiomeHelp.TAIGA_HILLS.id;
					} else if (var9 == BiomeHelp.PLAINS.id) {
						var10 = BiomeHelp.FOREST.id;
					} else if (var9 == BiomeHelp.ICE_PLAINS.id) {
						var10 = BiomeHelp.ICE_MOUNTAINS.id;
					} else if (var9 == BiomeHelp.JUNGLE.id) {
						var10 = BiomeHelp.JUNGLE_HILLS.id;
					}

					if (var10 != var9) {
						int var11 = var5[var8 + 1 + (var7 + 1 - 1) * (sizeX + 2)];
						int var12 = var5[var8 + 1 + 1 + (var7 + 1) * (sizeX + 2)];
						int var13 = var5[var8 + 1 - 1 + (var7 + 1) * (sizeX + 2)];
						int var14 = var5[var8 + 1 + (var7 + 1 + 1) * (sizeX + 2)];

						if (var11 == var9 && var12 == var9 && var13 == var9 && var14 == var9) {
							var6[var8 + var7 * sizeX] = var10;
						} else {
							var6[var8 + var7 * sizeX] = var9;
						}
					} else {
						var6[var8 + var7 * sizeX] = var9;
					}
				} else {
					var6[var8 + var7 * sizeX] = var9;
				}
			}
		}

		return var6;
	}
}