
package me.heldplayer.HeldGeneration.GenLayers;

public class GenLayerIsland extends GenLayer {
    public GenLayerIsland(long seed) {
        super(seed);
    }

    /**
     * Returns a list of integer values generated by this layer. These may be
     * interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer
     * subclass.
     */
    @Override
    public int[] getInts(int startX, int startZ, int sizeX, int sizeZ) {
        int[] var5 = IntCache.getIntCache(sizeX * sizeZ);

        for (int var6 = 0; var6 < sizeZ; ++var6) {
            for (int var7 = 0; var7 < sizeX; ++var7) {
                initChunkSeed((startX + var7), (startZ + var6));
                var5[var7 + var6 * sizeX] = nextInt(10) == 0 ? 1 : 0;
            }
        }

        if (startX > -sizeX && startX <= 0 && startZ > -sizeZ && startZ <= 0) {
            var5[-startX + -startZ * sizeX] = 1;
        }

        return var5;
    }
}
